name: Network and Security Configuration Settings
req_category: Network-Resource-Availability

requirement: 1. Moxa shall provide guidelines for recommended network and security configurations. 2. All Moxa devices shall provide an interface to allow access to the currently deployed network and security configuration settings.

design_guide: 1. Moxa host-based devices support default configuration for recommended network. For security configuration, user manual shall specify guidelines, or supports security wizard. 2. Moxa host-based devices provide access portal (ex, console, ...) to allow access to the currently deployed network and security configuration settings.

solution: Make sure mx-security and sshd packages are installed. 

package:
  - mx-security
  - ssh

service:
  enable:
  disable:

run:

cmd:

cmd_description:

