name: IACS Backup 

req_category: Network-Resource-Availability

requirement: 1. All Moxa devices shall provide the ability to verify the reliability of backup mechanisms and information integrity. 2. All Moxa devices shall employ appropriate mechanisms to protect the integrity of the information backed up.

design_guide: Moxa host-based device shall support the mechanism to protect the integrity of the information backed up. Example: 1. Digital signatures; 2. hashes

solution: The utility provides a feature to record the md5 checksum of each backup file. 

package:

service:
  enable:
  disable:

run:

cmd:

cmd_description:

